### ISSUE TITLE
How to run the tests

### ISSUE THREAD

**Issue by fabi321** [DzenanJupic/rustube#26]
I wanted to run the tests but didn't find any way to run them. Neither in the Readme, nor in the test source code. It would be nice to find such an explanation somewhere.

**Comment by DzenanJupic** [comment]
@fabi321 thank you for the question. How to run tests depends on which tests you want to run.
- If you want to run all 'normal' tests, then `cargo test` will do the job.
- If you want to run only tests that start with `foobar`, including `foobar1`, you can specify it like `cargo test foobar`
- If you want to run only tests that are called `foobar`, not including `foobar1`, you can add a `--exact` flag after a `--` separator (i.e. `cargo test foobar -- --exact`)
- If you want to run all tests that have an `#[ignored]` attribute, like `download_to_dir`, you have to add an `--ignored` flag  after the separator (i.e. `cargo test -- --ignored`)

You can also combine multiple of these methods, like i.e. `--exact` and `--ignored`.

For an example, have a look at [./.gihub/workflows/check_build_and_test.yml](https://github.com/DzenanJupic/rustube/blob/master/.github/workflows/check_build_and_test.yml).
Also, the rust book talks about it in [this chapter](https://github.com/DzenanJupic/rustube/blob/master/.github/workflows/check_build_and_test.yml).

**Comment by DzenanJupic** [comment]
I should add, that our tests currently don't have feature gates and therefore will fail to compile when running `cargo test` without the `--all-features` flag.
