### ISSUE TITLE
Return download url without actually executing .download()

### ISSUE THREAD

**Issue by hcbt** [DzenanJupic/rustube#27]
I've read the documentation and couldn't find such an option. I guess building url by filtering output of Video would be an option but is there a better way to do this? Thanks!

**Comment by DzenanJupic** [comment]
Hey, @hcbt thank you for your question.
The download URL is actually a bit hidden, and you're right that I should add a hint to the documentation. You can access each `Stream`s download URL via the `signature_cipher` filed, which contains a `url` field.
I'll add a hint to the documentation in the next release.

**Comment by hcbt** [comment]
Thanks!
