### ISSUE TITLE
Downloading gives an error: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: QueryDeserialization(Custom("missing field `player_response`"))'

### ISSUE THREAD

**Issue by joelimgu** [DzenanJupic/rustube#36]
Hello, 
I am trying to use your crate for a simple project as it seems to be the most advanced one. I really like how it should work but I am unable to make it download a video. I've tried multible ways but they all go back to the same error : 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: QueryDeserialization(Custom("missing field `player_response`"))'

the simple code is your example code:
```rust
#[rustube::tokio::main]
async fn main() {
    let url = "https://www.youtube.com/watch?v=Edx9D2yaOGs&ab_channel=CollegeHumor";
    println!("downloaded video to {:?}", rustube::download_best_quality(&url).await.unwrap());
}
```

I am pretty new to rust so this might be a simple fix, but I am unable to find what might be causing this. 
Thanks a lot!

**Comment by joelimgu** [comment]
Sorry, I only had to update. I hope this helps someone at least!

**Comment by fabi321** [comment]
This seems to be a bug related to the deserialisation, but I unfortunately cannot reproduce it on my machine.
```
downloaded video to "Edx9D2yaOGs.mp4"
```
This means that it looks like this is a bug between the library and youtube, not your usecase.

What version of rustube are you using?

**Comment by DzenanJupic** [comment]
Welcome to rustube @joelimguas. I'm glad to see that you and @fabi321 already figured out the solution to your problem.
The YouTube API is quite unstable, so in general older versions of `rustube` won't work anymore. 

Feel free to open issues or start discussions whenever you encounter problems or have proposals for a new feature / a design change.
