### ISSUE TITLE
Consider moving away from nightly-only features

### ISSUE THREAD

**Issue by DCNick3** [DzenanJupic/rustube#45]
First of all, thanks for creating and maintaining this library, which allows me to download youtube videos without introducing dependencies on python or other heavy stuff.

Currently this library uses a number of nightly-only features of the compiler. While they are nice, requiring nightly compiler threatens with code breakage and generally increases maintenance burden on the library users.

Looking at the features used, most (all?) of them can be removed by writing code that is a bit more verbose, adding a dependency (notably - there is `once_cell` crate) or using some attr tricks (for `doc(cfg)`).

How would you look at me landing a PR that would try to reduce number of nightly-only features used?

**Comment by DzenanJupic** [comment]
Hey @DCNick3, thanks for opening this issue. I already thought about doing that for quite some time, so you're welcome to open a PR!

**Comment by DzenanJupic** [comment]
Especially now since the build is failing due to a change in the `once_cell` feature.
