### ISSUE TITLE
How do you specify the download path for the video?

### ISSUE THREAD

**Issue by suitchi** [DzenanJupic/rustube#54]
### Description

How can I specify where to download the videos to? 

### Version

```text
0.6.0
```

**Comment by suitchi** [comment]
@DzenanJupic

**Comment by DzenanJupic** [comment]
Hey @suitchi, you can find the relevant documentation on `docs.rs`. For specifying the download path you can use [`Stream::download_to`](https://docs.rs/rustube/latest/rustube/struct.Stream.html#method.download_to).

**Comment by DzenanJupic** [comment]
Hey @suitchi, thanks for the feedback. 

I tried to make the `crate` level documentation quite extensive from the beginning on. There's also a part about these download functions: [different-ways-of-downloading](https://docs.rs/rustube/latest/rustube/index.html#different-ways-of-downloading). But I guess as the one who wrote this I cannot really judge what parts aren't enough documented.

Could elaborate on what you'd like to see specifically?
