### ISSUE TITLE
blocking_download_to_with_callback is not found

### ISSUE THREAD

**Issue by HusseinDossoki** [DzenanJupic/rustube#55]
### Description

I've installed the **rustube** throw the cargo and also tried reference to the GitHub repository and still can not access the **blocking_download_to_with_callback** method to download the video will Callback.

Cargo.toml
`rustube = { git = "https://github.com/DzenanJupic/rustube", branch = "master" }`
`rustube = "0.6.0"`

![image](https://user-images.githubusercontent.com/16858417/211337092-ea31c5cb-5feb-4aae-b101-51f983129ea0.png)

**Comment by matejrisek** [comment]
Hi there, beginner at Rust here, from what I can tell [you're missing `callback` feature](https://github.com/DzenanJupic/rustube/blob/bf08be2b0ec42c2ef5138352f19ff6e8da03b2a5/Cargo.toml#L62), which is not included in the default set. [blocking_download_to_with_callback depends on it](https://github.com/DzenanJupic/rustube/blob/bf08be2b0ec42c2ef5138352f19ff6e8da03b2a5/src/stream/mod.rs#L409).

`rustube = { version = "0.6.0", features = ["callback"] }` should bring to the context for you.

**Comment by HusseinDossoki** [comment]
> Hi there, beginner at Rust here, from what I can tell [you're missing the `callback` feature](https://github.com/DzenanJupic/rustube/blob/bf08be2b0ec42c2ef5138352f19ff6e8da03b2a5/Cargo.toml#L62), which is not included in the default set. [`blocking_download_to_with_callback` depends on it](https://github.com/DzenanJupic/rustube/blob/bf08be2b0ec42c2ef5138352f19ff6e8da03b2a5/src/stream/mod.rs#L409).
> 
> `rustube = { version = "0.6.0", features = ["callback"] }` should bring it to the context for you.

It works fine, thanks very much :)
